/**
 * Mule Zuora Cloud Connector
 *
 * Copyright (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 *
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 */


package com.zuora.api;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.1
 * 2012-08-28T17:54:23.357-03:00
 * Generated source version: 2.5.1
 */

@WebFault(name = "InvalidTypeFault", targetNamespace = "http://fault.api.zuora.com/")
public class InvalidTypeFault extends Exception {
    
    private com.zuora.api.fault.InvalidTypeFault invalidTypeFault;

    public InvalidTypeFault() {
        super();
    }
    
    public InvalidTypeFault(String message) {
        super(message);
    }
    
    public InvalidTypeFault(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidTypeFault(String message, com.zuora.api.fault.InvalidTypeFault invalidTypeFault) {
        super(message);
        this.invalidTypeFault = invalidTypeFault;
    }

    public InvalidTypeFault(String message, com.zuora.api.fault.InvalidTypeFault invalidTypeFault, Throwable cause) {
        super(message, cause);
        this.invalidTypeFault = invalidTypeFault;
    }

    public com.zuora.api.fault.InvalidTypeFault getFaultInfo() {
        return this.invalidTypeFault;
    }
}
