
package com.zuora.api;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.1
 * 2012-08-28T17:54:23.571-03:00
 * Generated source version: 2.5.1
 */

@WebFault(name = "InvalidValueFault", targetNamespace = "http://fault.api.zuora.com/")
public class InvalidValueFault extends Exception {
    
    private com.zuora.api.fault.InvalidValueFault invalidValueFault;

    public InvalidValueFault() {
        super();
    }
    
    public InvalidValueFault(String message) {
        super(message);
    }
    
    public InvalidValueFault(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidValueFault(String message, com.zuora.api.fault.InvalidValueFault invalidValueFault) {
        super(message);
        this.invalidValueFault = invalidValueFault;
    }

    public InvalidValueFault(String message, com.zuora.api.fault.InvalidValueFault invalidValueFault, Throwable cause) {
        super(message, cause);
        this.invalidValueFault = invalidValueFault;
    }

    public com.zuora.api.fault.InvalidValueFault getFaultInfo() {
        return this.invalidValueFault;
    }
}
