/**
 * Mule Development Kit
 * Copyright 2010-2011 (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * This file was automatically generated by the Mule Development Kit
 */
package org.mule.modules;

import org.mule.api.annotations.Configurable;
import org.mule.api.annotations.Module;
import org.mule.api.annotations.Processor;
import org.mule.api.annotations.lifecycle.Start;

import java.util.List;

@Module(name="zuora",
        namespace="http://repository.mulesoft.org/releases/org/mule/modules/mule-module-zuora",
        schemaLocation="http://repository.mulesoft.org/releases/org/mule/modules/mule-module-zuora/1.0-SNAPSHOT/mule-zuora.xsd")
public class ZuoraModule
{
    @Configurable
    private String username;
    @Configurable
    private String password;
    
    /**
     * Batch creation of ZObjects associated to Subscriptions
     *
     * {@code <subscribe subscriptions-ref="#[variable:subscribtions]"/>} 
     * @param subscriptions
     */
    @Processor
    public void subscribe(List<Object> subscriptions){
        
    }

    /**
     * Batch creation of ZObjects
     *
     * {@code <create>
     *          <zobjects>
     *              <zobject ref="#[variable:anObject]"/>
     *           </zobject>
     *         </create>}   
     * @param zobjects
     */
    @Processor
    public void create(List<Object> zobjects){
        
    }
    
    /**
     * Batch creation of invoces for accounts
     * 
     * {@code <generate zobjects-ref="#[variable:accounts]"/>}
     * @param zobjects
     */
    @Processor
    public void generate(List<Object> zobjects){
        
    }

    /**
     * Batch update of ZObjects
     *
     * {@code <update zobjects-ref="#[variable:objects]"/>}
     * @param zobjects
     */
    @Processor
    public void update(List<Object> zobjects)
    {

    }
    
    /**
     * Batch delete of ZObjects
     * 
     * {@code <delete zobjects-ref="#[variable:objects]"/>}
     * @param zobjects
     */
    @Processor
    public void delete(List<Object> zobjects)
    {

    }
    
    /**
     * Lazily retrieves ZObject that match a given query, 
     * written in Zuora native query language
     *
     * {@code <find query="#[header:queryString]" />}
     * @param zquery
     */
    @Processor
    public void find(String zquery)
    {
        
    }
    
    /**
     * Answers user information
     *
     * {@code <get-user-info userId="#[header:userId]""/>}
     * @param userid
     */
    @Processor
    public void getUserInfo(String userid){
        
    }
    
    /**
     * Amends subscriptions
     *
     * {@code <amend amendaments-ref="#[header:amendamentsList]"/>}
     * @param amendaments
     */
    @Processor
    public void amend(List<Object> amendaments)
    {

    }    
    
    //@Start
    public void init() throws Exception
    {
        
    }
    
    public String getPassword()
    {
        return password;
    }
    
    public String getUsername()
    {
        return username;
    }
    
    public void setPassword(String password)
    {
        this.password = password;
    }
    
    public void setUsername(String username)
    {
        this.username = username;
    }
    
}
