/**
 * Mule Development Kit
 * Copyright 2010-2011 (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * This file was automatically generated by the Mule Development Kit
 */

package org.mule.modules.zuora;

import com.zuora.api.DeleteResult;
import com.zuora.api.SaveResult;
import com.zuora.api.object.Account;
import com.zuora.api.object.ZObject;

import java.util.Arrays;
import java.util.Iterator;
import java.util.List;

import org.junit.Before;
import org.junit.Test;

import static org.junit.Assert.*;

public class ZuoraModuleTestDriver
{
    private ZuoraModule module;

    @Before
    public void setup() throws Exception
    {
        module = new ZuoraModule();
        module.setPassword(System.getenv("zuoraPassword"));
        module.setUsername(System.getenv("zuoraUsername"));
        module.init();
    }

    @Test
    public void createAndDelete() throws Exception
    {
        SaveResult result = module.create(Arrays.<ZObject> asList(new Account())).get(0);
        assertTrue(result.getSuccess());
        DeleteResult deleteResult = module.delete("Account", Arrays.asList(result.getId())).get(0);
        assertTrue(deleteResult.getSuccess());
    }

    @Test
    public void testname() throws Exception
    {
        Iterator<ZObject> result = module.find("SELECT Id FROM Account").iterator();
        assertTrue(result.hasNext());
        assertFalse(result.hasNext());
    }

}
